### ISSUE TITLE
User note command

### ISSUE THREAD

**Issue by fisher60** [fisher60/friendo-bot#170]
# Summary
This command is purely for fun. It will be quite spammy. The command will allow users to add public notes on another user. These will all be displayed when showing the notes for a single user.

# Implementation
The notes will be added to a paginated embed, this will also be the first command to utilize the graphql api. It will act as a bit of a dry run to see how we will integrate the api and what needs to change on the api for it to be effective.

**Comment by saiTama-max** [comment]
seems fun to me haha

**Comment by fisher60** [comment]
Closing as this does not fit the current direction of friendo bot.
