### ISSUE TITLE
Display incorrect usage of commands to the users

### ISSUE THREAD

**Issue by GDWR** [fisher60/friendo-bot#187]
Discord raises errors when a BadArgument/invalid argument is used in a command

```
discord.ext.commands.errors.BadArgument: Converting to "int" failed for parameter "amount".
```
This can be caught and used to tell the users why a command hasn't activated, helping with User Experience

**Comment by Slushs** [comment]
Can't you just have it equal to None. And just have an if statement?

**Comment by KJ002** [comment]
Is this still being worked on?
