### ISSUE TITLE
Add moderation tools

### ISSUE THREAD

**Issue by AnotherWorkaholic** [fisher60/friendo-bot#32]
I will be uploading it to my fork until it's complete.

**Comment by fisher60** [comment]
This is still an important change. There is not a lot we need to add, but we should implement the boilerplate for moderation. This will mostly be quality of life stuff.

**Comment by GDWR** [comment]
This issue is stale and lacks a fundamental definition of what is missing to be implemented. This issue can be reopened if more information is detailed so somebody can continue work.
